export const types = {
  FETCH_SELF_WORKSPACES: "FETCH_SELF_WORKSPACES",
  FETCH_WORKSPACES: "FETCH_WORKSPACES",
  CREATE_WORKSPACE: "CREATE_WORKSPACE",
  UPDATE_WORKSPACE: "UPDATE_WORKSPACE",
  DELETE_WORKSPACE: "DELETE_WORKSPACE",
  FETCH_WORKSPACE_INVITES: "FETCH_WORKSPACE_INVITES",
  RESPOND_TO_INVITE_WORKSPACE: "RESPOND_TO_INVITE_WORKSPACE",
  FETCH_WORKSPACES_SELECTOR: "FETCH_WORKSPACES_SELECTOR",
  SET_CURRENT: "SET_CURRENT",
};
