export const types = {
  FETCH_SELF_WORKSPACES: "FETCH_SELF_WORKSPACES",
  FETCH_WORKSPACES: "FETCH_WORKSPACES",
  CREATE_WORKSPACE: "CREATE_WORKSPACE",
  UPDATE_WORKSPACE: "UPDATE_WORKSPACE",
  DELETE_WORKSPACE: "DELETE_WORKSPACE",
  FETCH_WORKSPACES_SELECTOR: "FETCH_WORKSPACES_SELECTOR",
  SET_CURRENT_WORKSPACE: "SET_CURRENT_WORKSPACE",
  UPDATE_WORKSPACE_USERS: "UPDATE_WORKSPACE_USERS",
};
