export const types = {
  FETCH_SELF_SURVEY_PROGRAMS: "FETCH_SELF_SURVEY_PROGRAMS",
  FETCH_SURVEY_PROGRAMS: "FETCH_SURVEY_PROGRAMS",
  CREATE_SURVEY_PROGRAM: "CREATE_SURVEY_PROGRAM",
  FETCH_SURVEY_PROGRAM_STATISTICS: "FETCH_SURVEY_PROGRAM_STATISTICS",
  UPDATE_SURVEY_PROGRAM: "UPDATE_SURVEY_PROGRAM",
  DELETE_SURVEY_PROGRAM: "DELETE_SURVEY_PROGRAM",
  UPDATE_SURVEY_PROGRAM_USERS: "UPDATE_SURVEY_PROGRAM_USERS",
};
