export const types = {
  FETCH_SELF_PROJECTS: "FETCH_SELF_PROJECTS",
  FETCH_PROJECTS: "FETCH_PROJECTS",
  CREATE_PROJECT: "CREATE_PROJECT",
  UPDATE_PROJECT: "UPDATE_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
  FETCH_PROJECT_INVITES: "FETCH_PROJECT_INVITES",
  RESPOND_TO_INVITE_PROJECT: "RESPOND_TO_INVITE_PROJECT",
};
