export const types = {
  FETCH_SELF_PROJECTS: "FETCH_SELF_PROJECTS",
  FETCH_PROJECTS: "FETCH_PROJECTS",
  CREATE_PROJECT: "CREATE_PROJECT",
  UPDATE_PROJECT: "UPDATE_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
  UPDATE_PROJECT_USERS: "UPDATE_PROJECT_USERS",
  SET_CURRENT_PROJECT: "SET_CURRENT_PROJECT",
};
